# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a52fb335035841b3ffef9698105737f0ee02b38d7c19a62eb88a59a827b21b97f9de1a20ffd2294cf718ed803fedd98c4d9c81292b8c1a261548b89ceccc16d

test:
  secret_key_base: d3131f319aecf9f53383cc2842e06bf94dc9ea04346e50f635578b9779196812cc95c3fbf8172c00e36b6a9566b441e615d5712a72d0ec1429791788562b17bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
